//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

namespace StockCube
{
	public interface IStateMachine<T>
	{
		IState<T> CurrentState
		{
			get;
		}

        IState<T> PreviousState
        {
            get;
        }

        void Update();
		void AddState( IState<T> state );
		bool ChangeState( IState<T> state );
		bool ChangeState(T stateID); //state could be an int, string, Enum...
	}
}


